### ISSUE TITLE
flaky test: ioctl_test

### ISSUE THREAD

**Issue by zhijian-pro** [juicedata/juicefs#3762] opened 2023-06-05 09:38 UTC
https://github.com/juicedata/juicefs/actions/runs/5175461118/jobs/9323071302
 ```    
 3. finish................ 
 3. finish................ pass
        <- summary for `http': of 4 tests run: 4 passed, 0 failed. 100.0%
        bash ioctl_test.sh /tmp/jfs-unit-test/ioctl_test 2>/dev/null
        sudo chattr "+a" $a_test_dir/adir should success
        ioctl test failed
        make: *** [Makefile:33: ioctl] Error 1
```

**Comment by Hexilee** [comment] 2023-06-08 06:34
https://github.com/juicedata/juicefs/actions/runs/5208048099/jobs/9396212063?pr=3772

**Comment by zhijian-pro** [comment] 2023-07-24 02:27
Another problem about `ioctl` #2672

**Comment by SandyXSD** [comment] 2023-07-26 08:45
duplicate of #2672

**Closed by SandyXSD** 2023-07-26 08:45 UTC
