### ISSUE TITLE
DUMP: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by solracsf** [juicedata/juicefs#3821] opened 2023-06-18 08:30 UTC
**How to reproduce it (as minimally and precisely as possible)**:

```
juicefs dump badger:///metadata /tmp/badger.dump
2023/06/18 10:26:34.961384 juicefs[293315] <INFO>: Meta address: badger:///metadata [interface.go:401]
2023/06/18 10:26:35.049538 badger[293315] <INFO>: All 10 tables opened in 7ms [logger.go:46]
2023/06/18 10:26:35.054657 badger[293315] <INFO>: Discard stats nextEmptySlot: 0 [logger.go:46]
2023/06/18 10:26:35.055216 badger[293315] <INFO>: Set nextTxnTs to 7272124 [logger.go:46]
2023/06/18 10:26:35.055615 badger[293315] <INFO>: Deleting empty file: /metadata/000041.vlog [logger.go:46]
2023/06/18 10:26:35.455566 juicefs[293315] <WARNING>: Secret key is removed for the sake of safety [tkv.go:2571]
     Scan keys count: 51904 / 51904 [==============================================================]  done
Dumped entries count: 4580 / 21356 [============>-------------------------------------------------]  21 %    0s
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/juicedata/juicefs/pkg/meta.(*kvMeta).DumpMeta.func1()
        /go/src/github.com/juicedata/juicefs/pkg/meta/tkv.go:2398 +0x45
panic({0x28005e0, 0x46b1900})
        /usr/local/go/src/runtime/panic.go:890 +0x262
github.com/juicedata/juicefs/pkg/meta.(*kvMeta).dumpDir(0xc00063aea0, 0xc001dd65d0?, 0xc00d9b89b0?, 0xc000698b40, 0xb, 0xc003855590)
        /go/src/github.com/juicedata/juicefs/pkg/meta/tkv.go:2371 +0x871
github.com/juicedata/juicefs/pkg/meta.(*kvMeta).dumpDir(0xc00063aea0, 0xc002634f90?, 0xc00254bd10?, 0xc000698b40, 0x9, 0xc003855590)
        /go/src/github.com/juicedata/juicefs/pkg/meta/tkv.go:2377 +0x8f6
github.com/juicedata/juicefs/pkg/meta.(*kvMeta).dumpDir(0xc00063aea0, 0xc00dd505d0?, 0xc00dd0db98?, 0xc000698b40, 0x7, 0xc003855590)
        /go/src/github.com/juicedata/juicefs/pkg/meta/tkv.go:2377 +0x8f6
github.com/juicedata/juicefs/pkg/meta.(*kvMeta).dumpDir(0xc00063aea0, 0xc000607e00?, 0xc00dd0c1a0?, 0xc000698b40, 0x5, 0xc003855590)
        /go/src/github.com/juicedata/juicefs/pkg/meta/tkv.go:2377 +0x8f6
github.com/juicedata/juicefs/pkg/meta.(*kvMeta).dumpDir(0xc00063aea0, 0xc000606d80?, 0xc00dccd8b0?, 0xc000698b40, 0x3, 0xc003855590)
        /go/src/github.com/juicedata/juicefs/pkg/meta/tkv.go:2377 +0x8f6
github.com/juicedata/juicefs/pkg/meta.(*kvMeta).dumpDir(0xc00063aea0, 0x536c?, 0xc0004a0100?, 0xc000698b40, 0x1, 0xc003855590)
        /go/src/github.com/juicedata/juicefs/pkg/meta/tkv.go:2377 +0x8f6
github.com/juicedata/juicefs/pkg/meta.(*kvMeta).DumpMeta(0xc00063aea0, {0x328b220, 0xc0004a01f8}, 0x1)
        /go/src/github.com/juicedata/juicefs/pkg/meta/tkv.go:2594 +0x1651
github.com/juicedata/juicefs/cmd.dump(0xc000698840)
        /go/src/github.com/juicedata/juicefs/cmd/dump.go:73 +0x36c
github.com/urfave/cli/v2.(*Command).Run(0xc0007d85a0, 0xc000698740)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/command.go:163 +0x5dc
github.com/urfave/cli/v2.(*App).RunContext(0xc00070a4e0, {0x32a1f00?, 0xc0000540a8}, {0xc000698240, 0x4, 0x4})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:313 +0xb7d
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:224
github.com/juicedata/juicefs/cmd.Main({0xc0006980c0?, 0x4?, 0x4?})
        /go/src/github.com/juicedata/juicefs/cmd/main.go:86 +0x258d
2023/06/18 10:26:35.566299 juicefs[293315] <FATAL>: runtime error: invalid memory address or nil pointer dereference [main.go:31]
```

**Environment**:
- JuiceFS version:   1.0.4+2023-04-06.f1c475d
- OS: Ubuntu         22.04.2
- Kernel:                 5.15.0-75-generic
- Metadata:            BadgerDB

**Comment by solracsf** [comment] 2023-06-18 08:56
Test also with `juicefs version 1.1.0-beta1+2023-06-08.5ef17ba`, same result.

**Comment by Hexilee** [comment] 2023-06-19 03:25
Thanks for your report, could you provide the `badger:///metadata` directory for us to reproduce this problem?

**Comment by SandyXSD** [comment] 2023-06-19 03:38
It's probably caused by missing attribute for some inode. Can you also check the `juicefs.log` to see if there's any ERROR log?

**Comment by Hexilee** [comment] 2023-06-19 03:59
Could you try `juicefs fsck badger:///metadata --path / --recursive` to check if any attribute missing?

**Comment by solracsf** [comment] 2023-06-19 05:54
```
# juicefs fsck badger:///metadata --path / --recursive
2023/06/19 07:50:11.102535 juicefs[444590] <FATAL>: unknown option: --path [main.go:220]

# juicefs fsck badger:///metadata
2023/06/19 07:50:22.745270 juicefs[444598] <INFO>: Meta address: badger:///metadata [interface.go:401]
2023/06/19 07:50:22.864867 badger[444598] <INFO>: All 10 tables opened in 8ms [logger.go:46]
2023/06/19 07:50:22.867543 badger[444598] <INFO>: Discard stats nextEmptySlot: 0 [logger.go:46]
2023/06/19 07:50:22.867642 badger[444598] <INFO>: Set nextTxnTs to 7286481 [logger.go:46]
2023/06/19 07:50:22.868026 badger[444598] <INFO>: Deleting empty file: /metadata/000041.vlog [logger.go:46]
2023/06/19 07:50:22.907843 juicefs[444598] <INFO>: Data use s3://ceezy/juicefs/(encrypted) [fsck.go:73]
2023/06/19 07:50:25.605826 juicefs[444598] <WARNING>: Get directory path of 586745: entry 561447/586744 not found [interface.go:474]
2023/06/19 07:50:25.605874 juicefs[444598] <ERROR>: can't find block 0/535/535260_0_59 for file inode:586746: file does not exist [fsck.go:146]
2023/06/19 07:50:25.635235 juicefs[444598] <WARNING>: Get directory path of 586738: getattr inode 586738: no such file or directory [interface.go:474]
2023/06/19 07:50:25.635290 juicefs[444598] <ERROR>: can't find block 0/535/535257_0_1822 for file inode:586739: file does not exist [fsck.go:146]
2023/06/19 07:50:25.670398 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 7578, but got 0 [interface.go:493]
2023/06/19 07:50:25.670443 juicefs[444598] <ERROR>: can't find block 0/530/530288_0_3054 for file inode:585726: file does not exist [fsck.go:146]
2023/06/19 07:50:25.709945 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 558432, but got 0 [interface.go:493]
2023/06/19 07:50:25.709991 juicefs[444598] <ERROR>: can't find block 0/510/510005_0_68321 for file inode:562505: file does not exist [fsck.go:146]
2023/06/19 07:50:25.805866 juicefs[444598] <ERROR>: can't find block 0/534/534145_0_1754 for file /data/appdata_ocsbtdk3kg5v/preview/8/1/a/9/e/6/b/1266720/256-256-crop.jpg: file does not exist [fsck.go:146]
2023/06/19 07:50:25.852302 juicefs[444598] <WARNING>: Get directory path of 586742: entry 561447/586741 not found [interface.go:474]
2023/06/19 07:50:25.852345 juicefs[444598] <ERROR>: can't find block 0/535/535259_0_101 for file inode:586743: file does not exist [fsck.go:146]
2023/06/19 07:50:25.887221 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 557859, but got 0 [interface.go:493]
2023/06/19 07:50:25.887263 juicefs[444598] <ERROR>: can't find block 0/506/506266_0_22536 for file inode:561150: file does not exist [fsck.go:146]
2023/06/19 07:50:25.921306 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 532438, but got 0 [interface.go:493]
2023/06/19 07:50:25.921348 juicefs[444598] <ERROR>: can't find block 0/510/510004_0_53813 for file inode:562504: file does not exist [fsck.go:146]
2023/06/19 07:50:25.957611 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 562043, but got 0 [interface.go:493]
2023/06/19 07:50:25.957669 juicefs[444598] <ERROR>: can't find block 0/535/535263_0_21493 for file inode:586750: file does not exist [fsck.go:146]
2023/06/19 07:50:26.007923 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 558434, but got 0 [interface.go:493]
2023/06/19 07:50:26.008020 juicefs[444598] <ERROR>: can't find block 0/504/504120_0_24551 for file inode:558584: file does not exist [fsck.go:146]
2023/06/19 07:50:26.045132 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 9551, but got 0 [interface.go:493]
2023/06/19 07:50:26.045203 juicefs[444598] <ERROR>: can't find block 0/530/530066_0_216583 for file inode:585723: file does not exist [fsck.go:146]
2023/06/19 07:50:26.079214 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 7586, but got 0 [interface.go:493]
2023/06/19 07:50:26.079257 juicefs[444598] <ERROR>: can't find block 0/532/532002_0_155 for file inode:585803: file does not exist [fsck.go:146]
2023/06/19 07:50:26.115973 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 561557, but got 0 [interface.go:493]
2023/06/19 07:50:26.116025 juicefs[444598] <ERROR>: can't find block 0/534/534148_0_5343 for file inode:586314: file does not exist [fsck.go:146]
2023/06/19 07:50:26.153739 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 562374, but got 0 [interface.go:493]
2023/06/19 07:50:26.153788 juicefs[444598] <ERROR>: can't find block 0/533/533109_0_872043 for file inode:585979: file does not exist [fsck.go:146]
2023/06/19 07:50:26.191277 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 7586, but got 0 [interface.go:493]
2023/06/19 07:50:26.191419 juicefs[444598] <ERROR>: can't find block 0/532/532001_0_344102 for file inode:585802: file does not exist [fsck.go:146]
2023/06/19 07:50:26.263114 juicefs[444598] <ERROR>: can't find block 0/506/506259_0_74858 for file /data/__groupfolders/versions/45/1265238/1680690894: file does not exist [fsck.go:146]
2023/06/19 07:50:26.297047 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 7578, but got 0 [interface.go:493]
2023/06/19 07:50:26.297087 juicefs[444598] <ERROR>: can't find block 0/530/530287_0_266 for file inode:585725: file does not exist [fsck.go:146]
2023/06/19 07:50:26.343268 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 3847, but got 0 [interface.go:493]
2023/06/19 07:50:26.343305 juicefs[444598] <ERROR>: can't find block 0/503/503006_0_54961 for file inode:558071: file does not exist [fsck.go:146]
2023/06/19 07:50:26.386831 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 585969, but got 0 [interface.go:493]
2023/06/19 07:50:26.386900 juicefs[444598] <ERROR>: can't find block 0/533/533105_0_879288 for file inode:585977: file does not exist [fsck.go:146]
2023/06/19 07:50:26.507002 juicefs[444598] <ERROR>: can't find block 0/534/534144_0_2927 for file /data/appdata_ocsbtdk3kg5v/preview/c/1/b/4/f/2/f/1266719/256-256-crop.jpg: file does not exist [fsck.go:146]
2023/06/19 07:50:26.549840 juicefs[444598] <WARNING>: Get directory path of 586748: entry 561447/586747 not found [interface.go:474]
2023/06/19 07:50:26.549881 juicefs[444598] <ERROR>: can't find block 0/535/535261_0_8082 for file inode:586749: file does not exist [fsck.go:146]
2023/06/19 07:50:26.587883 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 532438, but got 0 [interface.go:493]
2023/06/19 07:50:26.587938 juicefs[444598] <ERROR>: can't find block 0/533/533096_0_1259483 for file inode:585972: file does not exist [fsck.go:146]
2023/06/19 07:50:26.646111 juicefs[444598] <ERROR>: can't find block 0/507/507123_0_25931 for file /data/__groupfolders/versions/45/1260316/1681207631: file does not exist [fsck.go:146]
2023/06/19 07:50:26.689738 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 558273, but got 0 [interface.go:493]
2023/06/19 07:50:26.689794 juicefs[444598] <ERROR>: can't find block 0/507/507121_0_49994 for file inode:561478: file does not exist [fsck.go:146]
2023/06/19 07:50:26.727869 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 561136, but got 0 [interface.go:493]
2023/06/19 07:50:26.727923 juicefs[444598] <ERROR>: can't find block 0/506/506257_0_187404 for file inode:561145: file does not exist [fsck.go:146]
2023/06/19 07:50:26.769069 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 558434, but got 0 [interface.go:493]
2023/06/19 07:50:26.769131 juicefs[444598] <ERROR>: can't find block 0/507/507118_0_25473 for file inode:561477: file does not exist [fsck.go:146]
2023/06/19 07:50:26.810909 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 7578, but got 0 [interface.go:493]
2023/06/19 07:50:26.810970 juicefs[444598] <ERROR>: can't find block 0/530/530286_0_11942 for file inode:585724: file does not exist [fsck.go:146]
2023/06/19 07:50:26.855183 juicefs[444598] <WARNING>: Expect to find 1 entries under parent 533883, but got 0 [interface.go:493]
2023/06/19 07:50:26.855260 juicefs[444598] <ERROR>: can't find block 0/510/510001_0_41421 for file inode:562502: file does not exist [fsck.go:146]
  Found blocks count: 10390
  Found blocks bytes: 7.87 GiB (8448939196 Bytes)
 Listed slices count: 9263
Scanned slices count: 9263 / 9263 [==============================================================]  done
Scanned slices bytes: 8.78 GiB (9425225714 Bytes)
   Lost blocks count: 28
   Lost blocks bytes: 4.06 MiB (4257760 Bytes)
2023/06/19 07:50:26.858258 juicefs[444598] <FATAL>: 28 objects are lost (4257760 bytes), 28 broken files:
        INODE: PATH
       558071: inode:558071
       558584: inode:558584
       561145: inode:561145
       561146: /data/__groupfolders/versions/45/1265238/1680690894
       561150: inode:561150
       561477: inode:561477
       561478: inode:561478
       561479: /data/__groupfolders/versions/45/1260316/1681207631
       562502: inode:562502
       562504: inode:562504
       562505: inode:562505
       585723: inode:585723
       585724: inode:585724
       585725: inode:585725
       585726: inode:585726
       585802: inode:585802
       585803: inode:585803
       585972: inode:585972
       585977: inode:585977
       585979: inode:585979
       586305: /data/appdata_ocsbtdk3kg5v/preview/c/1/b/4/f/2/f/1266719/256-256-crop.jpg
       586312: /data/appdata_ocsbtdk3kg5v/preview/8/1/a/9/e/6/b/1266720/256-256-crop.jpg
       586314: inode:586314
       586739: inode:586739
       586743: inode:586743
       586746: inode:586746
       586749: inode:586749
       586750: inode:586750 [fsck.go:168]
```

**Comment by Hexilee** [comment] 2023-06-19 07:44
The `fsck` without `--path` only checks object loss. Please provide the full log of `juicefs fsck badger:///metadata --path / --recursive` by a text file.

**Comment by solracsf** [comment] 2023-06-19 08:20
@Hexilee I'll be hapy to provide it **by mail**, not in a public page as it contains sensitive data.

**Comment by SandyXSD** [comment] 2023-06-19 08:21
We found an issue that may wrongly report broken files, and are tracking it in #3830 .
However, the dump panic means there must be some keys lost in the Badger. Has the JuiceFS client ever been killed abnormally before?

**Comment by solracsf** [comment] 2023-06-19 08:23
I don't think so; everything is monitored and unless it has been killed and restarted (by systemd) there was no such thing like OOM, reboot or similar.

**Comment by solracsf** [comment] 2023-06-19 08:33
Sent.

**Comment by solracsf** [comment] 2023-06-20 10:20
```
root@cloud:/tmp# ./juicefs --version
juicefs version 1.1.0-dev+2023-06-20.4867ec41
```

### DUMP

```
root@cloud:/tmp# /juicefs dump badger:///srv/badgerbackup/latest /tmp/badger.dump
2023/06/20 12:19:35.773750 juicefs[616112] <INFO>: Meta address: badger:///srv/badgerbackup/latest [interface.go:494]
2023/06/20 12:19:35.789978 badger[616112] <INFO>: All 13 tables opened in 1ms [logger.go:46]
2023/06/20 12:19:35.790595 badger[616112] <INFO>: Discard stats nextEmptySlot: 0 [logger.go:46]
2023/06/20 12:19:35.790648 badger[616112] <INFO>: Set nextTxnTs to 7308846 [logger.go:46]
2023/06/20 12:19:35.790776 badger[616112] <INFO>: Deleting empty file: /srv/badgerbackup/latest/000053.vlog [logger.go:46]
2023/06/20 12:19:36.192694 juicefs[616112] <WARNING>: Secret key is removed for the sake of safety [tkv.go:3122]
2023/06/20 12:19:36.236064 juicefs[616112] <ERROR>: Corrupt inode: 557820, missing attribute [tkv.go:2878]
2023/06/20 12:19:36.236107 juicefs[616112] <ERROR>: Corrupt inode: 557820, missing attribute [tkv.go:2878]
2023/06/20 12:19:36.236125 juicefs[616112] <ERROR>: Corrupt inode: 557820, missing attribute [tkv.go:2878]
2023/06/20 12:19:36.236138 juicefs[616112] <ERROR>: Corrupt inode: 557820, missing attribute [tkv.go:2878]
2023/06/20 12:19:36.236244 juicefs[616112] <ERROR>: Corrupt inode: 533246, missing attribute [tkv.go:2878]
2023/06/20 12:19:36.236260 juicefs[616112] <ERROR>: Corrupt inode: 533246, missing attribute [tkv.go:2878]
2023/06/20 12:19:36.236403 juicefs[616112] <ERROR>: Corrupt inode: 585980, missing attribute [tkv.go:2878]
     Scan keys: 53849/53849 [==============================================================]  162706.9/s used: 330.965964ms
Dumped entries: 22080/22080 [==============================================================]  188321.2/s used: 117.268836ms
2023/06/20 12:19:36.311832 juicefs[616112] <INFO>: Dump metadata into /tmp/badger.dump succeed [dump.go:107]
```

### FSCK
```
root@cloud:/tmp# ./juicefs fsck badger:///srv/badgerbackup/latest
2023/06/20 12:17:30.874606 juicefs[616035] <INFO>: Meta address: badger:///srv/badgerbackup/latest [interface.go:494]
2023/06/20 12:17:30.884905 badger[616035] <INFO>: All 13 tables opened in 1ms [logger.go:46]
2023/06/20 12:17:30.885603 badger[616035] <INFO>: Discard stats nextEmptySlot: 0 [logger.go:46]
2023/06/20 12:17:30.885661 badger[616035] <INFO>: Set nextTxnTs to 7308846 [logger.go:46]
2023/06/20 12:17:30.885848 badger[616035] <INFO>: Deleting empty file: /srv/badgerbackup/latest/000052.vlog [logger.go:46]
2023/06/20 12:17:30.888213 juicefs[616035] <INFO>: Data use s3://ceezy/juicefs/(encrypted) [fsck.go:108]
2023/06/20 12:17:33.815893 juicefs[616035] <ERROR>: can't find block 0/506/506259_0_74858 for file /data/__groupfolders/versions/45/1265238/1680690894: file does not exist [fsck.go:196]
2023/06/20 12:17:33.859090 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 533883, but got 0 [base.go:1875]
2023/06/20 12:17:33.859138 juicefs[616035] <ERROR>: can't find block 0/510/510001_0_41421 for file inode:562502: file does not exist [fsck.go:196]
2023/06/20 12:17:33.906450 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 557859, but got 0 [base.go:1875]
2023/06/20 12:17:33.906503 juicefs[616035] <ERROR>: can't find block 0/506/506266_0_22536 for file inode:561150: file does not exist [fsck.go:196]
2023/06/20 12:17:33.948781 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 558273, but got 0 [base.go:1875]
2023/06/20 12:17:33.948829 juicefs[616035] <ERROR>: can't find block 0/507/507121_0_49994 for file inode:561478: file does not exist [fsck.go:196]
2023/06/20 12:17:33.993926 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 7578, but got 0 [base.go:1875]
2023/06/20 12:17:33.993976 juicefs[616035] <ERROR>: can't find block 0/530/530286_0_11942 for file inode:585724: file does not exist [fsck.go:196]
2023/06/20 12:17:34.051408 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 3847, but got 0 [base.go:1875]
2023/06/20 12:17:34.051459 juicefs[616035] <ERROR>: can't find block 0/503/503006_0_54961 for file inode:558071: file does not exist [fsck.go:196]
2023/06/20 12:17:34.164745 juicefs[616035] <ERROR>: can't find block 0/534/534145_0_1754 for file /data/appdata_ocsbtdk3kg5v/preview/8/1/a/9/e/6/b/1266720/256-256-crop.jpg: file does not exist [fsck.go:196]
2023/06/20 12:17:34.214578 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 562043, but got 0 [base.go:1875]
2023/06/20 12:17:34.214633 juicefs[616035] <ERROR>: can't find block 0/535/535263_0_21493 for file inode:586750: file does not exist [fsck.go:196]
2023/06/20 12:17:34.271487 juicefs[616035] <WARNING>: Get directory path of 586742: entry 561447/586741 not found [base.go:1856]
2023/06/20 12:17:34.271567 juicefs[616035] <ERROR>: can't find block 0/535/535259_0_101 for file inode:586743: file does not exist [fsck.go:196]
2023/06/20 12:17:34.331348 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 7578, but got 0 [base.go:1875]
2023/06/20 12:17:34.331400 juicefs[616035] <ERROR>: can't find block 0/530/530288_0_3054 for file inode:585726: file does not exist [fsck.go:196]
2023/06/20 12:17:34.390419 juicefs[616035] <ERROR>: can't find block 0/507/507123_0_25931 for file /data/__groupfolders/versions/45/1260316/1681207631: file does not exist [fsck.go:196]
2023/06/20 12:17:34.439451 juicefs[616035] <WARNING>: Get directory path of 586748: entry 561447/586747 not found [base.go:1856]
2023/06/20 12:17:34.439534 juicefs[616035] <ERROR>: can't find block 0/535/535261_0_8082 for file inode:586749: file does not exist [fsck.go:196]
2023/06/20 12:17:34.488432 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 532438, but got 0 [base.go:1875]
2023/06/20 12:17:34.488488 juicefs[616035] <ERROR>: can't find block 0/510/510004_0_53813 for file inode:562504: file does not exist [fsck.go:196]
2023/06/20 12:17:34.527538 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 7578, but got 0 [base.go:1875]
2023/06/20 12:17:34.527617 juicefs[616035] <ERROR>: can't find block 0/530/530287_0_266 for file inode:585725: file does not exist [fsck.go:196]
2023/06/20 12:17:34.624687 juicefs[616035] <ERROR>: can't find block 0/534/534144_0_2927 for file /data/appdata_ocsbtdk3kg5v/preview/c/1/b/4/f/2/f/1266719/256-256-crop.jpg: file does not exist [fsck.go:196]
2023/06/20 12:17:34.676863 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 561557, but got 0 [base.go:1875]
2023/06/20 12:17:34.676931 juicefs[616035] <ERROR>: can't find block 0/534/534148_0_5343 for file inode:586314: file does not exist [fsck.go:196]
2023/06/20 12:17:34.743448 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 562374, but got 0 [base.go:1875]
2023/06/20 12:17:34.743499 juicefs[616035] <ERROR>: can't find block 0/533/533109_0_872043 for file inode:585979: file does not exist [fsck.go:196]
2023/06/20 12:17:34.787865 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 7586, but got 0 [base.go:1875]
2023/06/20 12:17:34.787901 juicefs[616035] <ERROR>: can't find block 0/532/532002_0_155 for file inode:585803: file does not exist [fsck.go:196]
2023/06/20 12:17:34.830392 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 7586, but got 0 [base.go:1875]
2023/06/20 12:17:34.830431 juicefs[616035] <ERROR>: can't find block 0/532/532001_0_344102 for file inode:585802: file does not exist [fsck.go:196]
2023/06/20 12:17:34.873212 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 532438, but got 0 [base.go:1875]
2023/06/20 12:17:34.873246 juicefs[616035] <ERROR>: can't find block 0/533/533096_0_1259483 for file inode:585972: file does not exist [fsck.go:196]
2023/06/20 12:17:34.931801 juicefs[616035] <WARNING>: Get directory path of 586745: entry 561447/586744 not found [base.go:1856]
2023/06/20 12:17:34.931842 juicefs[616035] <ERROR>: can't find block 0/535/535260_0_59 for file inode:586746: file does not exist [fsck.go:196]
2023/06/20 12:17:34.976343 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 558432, but got 0 [base.go:1875]
2023/06/20 12:17:34.976376 juicefs[616035] <ERROR>: can't find block 0/510/510005_0_68321 for file inode:562505: file does not exist [fsck.go:196]
2023/06/20 12:17:35.018782 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 9551, but got 0 [base.go:1875]
2023/06/20 12:17:35.018817 juicefs[616035] <ERROR>: can't find block 0/530/530066_0_216583 for file inode:585723: file does not exist [fsck.go:196]
2023/06/20 12:17:35.064607 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 558434, but got 0 [base.go:1875]
2023/06/20 12:17:35.064642 juicefs[616035] <ERROR>: can't find block 0/507/507118_0_25473 for file inode:561477: file does not exist [fsck.go:196]
2023/06/20 12:17:35.111073 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 585969, but got 0 [base.go:1875]
2023/06/20 12:17:35.111111 juicefs[616035] <ERROR>: can't find block 0/533/533105_0_879288 for file inode:585977: file does not exist [fsck.go:196]
2023/06/20 12:17:35.160844 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 558434, but got 0 [base.go:1875]
2023/06/20 12:17:35.160885 juicefs[616035] <ERROR>: can't find block 0/504/504120_0_24551 for file inode:558584: file does not exist [fsck.go:196]
2023/06/20 12:17:35.220026 juicefs[616035] <WARNING>: Expect to find 1 entries under parent 561136, but got 0 [base.go:1875]
2023/06/20 12:17:35.220081 juicefs[616035] <ERROR>: can't find block 0/506/506257_0_187404 for file inode:561145: file does not exist [fsck.go:196]
2023/06/20 12:17:35.253761 juicefs[616035] <WARNING>: Get directory path of 586738: getattr inode 586738: no such file or directory [base.go:1856]
2023/06/20 12:17:35.253797 juicefs[616035] <ERROR>: can't find block 0/535/535257_0_1822 for file inode:586739: file does not exist [fsck.go:196]
  Found blocks: 10856                        4685.8/s
  Found blocks: 8.2 GiB (8793683062 Bytes)   3.5 GiB/s
 Listed slices: 9698                         54488.4/s
 Deleted files: 0                            0.0/s
Skipped slices: 0                            0.0/s
Scanned slices: 9698/9698 [==============================================================]  6446.8/s used: 1.504314131s
Scanned slices: 9.1 GiB (9815696056 Bytes)   6.1 GiB/s
   Lost blocks: 28                           18.6/s
   Lost blocks: 4.1 MiB (4257760 Bytes)      2.7 MiB/s
2023/06/20 12:17:35.256459 juicefs[616035] <FATAL>: 28 objects are lost (4257760 bytes), 28 broken files:
        INODE: PATH
       558071: inode:558071
       558584: inode:558584
       561145: inode:561145
       561146: /data/__groupfolders/versions/45/1265238/1680690894
       561150: inode:561150
       561477: inode:561477
       561478: inode:561478
       561479: /data/__groupfolders/versions/45/1260316/1681207631
       562502: inode:562502
       562504: inode:562504
       562505: inode:562505
       585723: inode:585723
       585724: inode:585724
       585725: inode:585725
       585726: inode:585726
       585802: inode:585802
       585803: inode:585803
       585972: inode:585972
       585977: inode:585977
       585979: inode:585979
       586305: /data/appdata_ocsbtdk3kg5v/preview/c/1/b/4/f/2/f/1266719/256-256-crop.jpg
       586312: /data/appdata_ocsbtdk3kg5v/preview/8/1/a/9/e/6/b/1266720/256-256-crop.jpg
       586314: inode:586314
       586739: inode:586739
       586743: inode:586743
       586746: inode:586746
       586749: inode:586749
       586750: inode:586750 [fsck.go:218]
```

**Comment by solracsf** [comment] 2023-06-20 10:40
If this helps, apparently this started hapening after a "massive" deletion of data _(one folder containing many subfolders+files)_, moving from 600Gib to 10Gib approx.

**Comment by davies** [comment] 2023-06-21 06:10
How do you delete the massive files? It will be great if you can find a way to reproduce this.

**Comment by solracsf** [comment] 2023-06-21 06:50
Files are managed trough a PHP script (Nextcloud) and those files where property of a single user. User was deleted, and so his files.

**Comment by solracsf** [comment] 2023-06-21 06:52
Is there any way to fix these fsck/dump errors even if it implies loosing some data/files? Because at https://juicefs.com/docs/community/administration/status_check_and_maintenance/#fsck we talk about the error, recovering files, but not how to fix these...

**Comment by davies** [comment] 2023-06-21 06:54
You can load into a new badgerdb with the dumped JSON file, then use the new one.

**Comment by Hexilee** [comment] 2023-06-21 08:44
> Is there any way to fix these fsck/dump errors even if it implies loosing some data/files? Because at https://juicefs.com/docs/community/administration/status_check_and_maintenance/#fsck we talk about the error, recovering files, but not how to fix these...

In the latest main branch, dump should ignore these broken entries, you can try it.

**Comment by solracsf** [comment] 2023-06-21 08:58
Yes, DUMP succeeds but FSCK still failing.
https://github.com/juicedata/juicefs/issues/3821?notification_referrer_id=NT_kwDOALqvDrM2ODAxMDI1ODcwOjEyMjM0NTEw#issuecomment-1598508396

**Comment by davies** [comment] 2023-06-22 01:14
It's expected that fsck report any corruption in your volume. Can you load the dumped JSON into a new badgerdb and run fsck on that?

**Comment by solracsf** [comment] 2023-06-22 05:55
Will do this weekend and report back. 👍

**Comment by solracsf** [comment] 2023-06-24 09:48
@davies how can I import to a new BadgerDB?

```
mkdir -p /opt/badger
./juicefs load /tmp/full.dump badger:///opt/badger
<FATAL>: open badger:///opt/badger: no such file or directory [main.go:31]
```

**Comment by davies** [comment] 2023-06-24 14:40
the first argument should be META-URL, then path of JSON file:
```
juicefs load badger:///tmp/newgadger2  /tmp/full.dump
```

**Comment by solracsf** [comment] 2023-06-24 17:23
_Sorry, it's the weekend... 😭 🤣_ 

So i've imported the new JSON, `fcsk` found a broken file:

```
juicefs[1491495] <FATAL>: 1 objects are lost (74858 bytes), 1 broken files:
        INODE: PATH
       561146: /data/__groupfolders/versions/45/1265238/1680690894 [fsck.go:168]
```
I've manually deleted that file to find a error-free `fsck`.

**Comment by davies** [comment] 2023-06-25 02:00
We have fixed the bug which cause panic in dump, let's close this one.

The cause of metadata corruption is still unknown, we can create a new one if it happen again.

**Closed by davies** 2023-06-25 02:00 UTC
Labels: kind/bug
