### ISSUE TITLE
cp a file to jfs mountpoint, Interrupted system call

### ISSUE THREAD

**Issue by fxmumu** [juicedata/juicefs#1456] opened 2022-02-21 02:02 UTC
**What happened**:
cp a file to jfs mountpoint, Interrupted system call 

**What you expected to happen**:
cp done, and file sync to awss3 bucket by jfs

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: juicefs version 0.17-dev
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:
jfs run in a container

**Comment by SandyXSD** [comment] 2022-02-21 02:36
Could you please add more details (hardwares, special arguments, reproduce steps etc.) about how to reproduce this issue?

**Comment by fxmumu** [comment] 2022-02-21 06:47
> Could you please add more details (hardwares, special arguments, reproduce steps etc.) about how to reproduce this issue?

OK, I will post the detail later.

**Comment by davies** [comment] 2022-04-22 05:39
The operations working with JuiceFS are interruptible for better user control. On the other side, they can be interrupted unexpectedly. The application should retry the interrupted operations,  but many don't.

We can't reproduce this, close it for now.

**Closed by davies** 2022-04-22 05:39 UTC
Labels: kind/bug, need-more-info
