### ISSUE TITLE
store meta info into redis which is not a strong consistency storage may cause meta info broken

### ISSUE THREAD

**Issue by arthurkiller** [juicedata/juicefs#287] opened 2021-04-07 09:32 UTC
**What would you like to be added**:

as we all know, `redis` use async replication for master slave data transport. However this consistency model can not provide a strong consistency on `redis master` crash, some times data may lost.

**Why is this needed**:

maybe you need a redis protocol supported storage which can provide strong concistency. just like https://github.com/distributedio/titan

**Comment by xiaogaozi** [comment] 2021-04-07 10:04
Duplicate of #183

**Closed by xiaogaozi** 2021-04-07 10:04 UTC
Labels: kind/feature
