### ISSUE TITLE
Crashed after mount

### ISSUE THREAD

**Issue by yunwoniu** [juicedata/juicefs#118] opened 2021-01-26 06:34 UTC
**What happened**:
执行挂载命令./juicefs --trace  mount localhost /root/jfs
```
fatal error: unexpected signal during runtime execution
[signal SIGBUS: bus error code=0x2 addr=0x1bbdc44 pc=0x468d19]

runtime stack:
runtime.throw(0x15f4d1b, 0x2a)
        /usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:704 +0x4ac
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000000300, 0x0, 0x0, 0x7fffffff, 0x1617e68, 0x7f8b05ffa9a8, 0x0, ...)
        /usr/local/go/src/runtime/traceback.go:189 +0x2b9
runtime.copystack(0xc000000300, 0x40000)
        /usr/local/go/src/runtime/stack.go:910 +0x287
runtime.shrinkstack(0xc000000300)
        /usr/local/go/src/runtime/stack.go:1178 +0x13d
runtime.scanstack(0xc000000300, 0xc00005ae98)
        /usr/local/go/src/runtime/mgcmark.go:815 +0x56e
runtime.markroot.func1()
        /usr/local/go/src/runtime/mgcmark.go:245 +0xc6
runtime.markroot(0xc00005ae98, 0x14)
        /usr/local/go/src/runtime/mgcmark.go:218 +0x310
runtime.gcDrain(0xc00005ae98, 0x7)
        /usr/local/go/src/runtime/mgcmark.go:1109 +0x118
runtime.gcBgMarkWorker.func2()
        /usr/local/go/src/runtime/mgc.go:1981 +0x177
runtime.systemstack(0xc000102900)
        /usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1116

goroutine 7 [GC worker (idle)]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc0000d0f60 sp=0xc0000d0f58 pc=0x479ba0
runtime.gcBgMarkWorker(0xc000059800)
        /usr/local/go/src/runtime/mgc.go:1945 +0x1be fp=0xc0000d0fd8 sp=0xc0000d0f60 pc=0x428d1e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000d0fe0 sp=0xc0000d0fd8 pc=0x47b981
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1839 +0x77

goroutine 1 [GC assist marking (scan), locked to thread]:
bytes.makeSlice(0x200, 0x0, 0x0, 0x0)
        /usr/local/go/src/bytes/buffer.go:229 +0x73
bytes.(*Buffer).grow(0xc0006479b0, 0x200, 0x0)
        /usr/local/go/src/bytes/buffer.go:142 +0x156
bytes.(*Buffer).Grow(...)
        /usr/local/go/src/bytes/buffer.go:161
io/ioutil.readAll(0x17a80e0, 0xc000491600, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:34 +0xa5
io/ioutil.ReadAll(...)
        /usr/local/go/src/io/ioutil/ioutil.go:45
google.golang.org/protobuf/internal/impl.legacyLoadFileDesc(0x218d6c0, 0x181, 0x181, 0x1, 0x0)
        /root/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/legacy_file.go:54 +0x178
google.golang.org/protobuf/internal/impl.legacyLoadMessageDesc(0x17e4260, 0x142d4a0, 0x15f55a5, 0x2b, 0x0, 0x0)
        /root/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/legacy_message.go:131 +0x357
google.golang.org/protobuf/internal/impl.legacyLoadMessageInfo(0x17e4260, 0x142d4a0, 0x15f55a5, 0x2b, 0x0)
        /root/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/legacy_message.go:48 +0xbd
google.golang.org/protobuf/internal/impl.Export.LegacyMessageTypeOf(0x17c0d60, 0x0, 0x15f55a5, 0x2b, 0x0, 0x0)
        /root/go/pkg/mod/google.golang.org/protobuf@v1.23.0/internal/impl/legacy_export.go:33 +0xa5
github.com/golang/protobuf/proto.RegisterType(0x17c0d60, 0x0, 0x15f55a5, 0x2b)
        /root/go/pkg/mod/github.com/golang/protobuf@v1.4.2/proto/registry.go:186 +0x4d
github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_common.init.22()
        /root/go/pkg/mod/github.com/colinmarc/hdfs/v2@v2.2.0/internal/protocol/hadoop_common/TraceAdmin.pb.go:160 +0x4f

goroutine 18 [sleep]:
time.Sleep(0x8bb2c97000)
        /usr/local/go/src/runtime/time.go:188 +0xbf
github.com/juicedata/juicefs/pkg/utils.init.0.func1()
        /mywork/juicefs/pkg/utils/alloc.go:65 +0x30
created by github.com/juicedata/juicefs/pkg/utils.init.0
        /mywork/juicefs/pkg/utils/alloc.go:63 +0x35

goroutine 19 [chan receive]:
github.com/baidubce/bce-sdk-go/util/log.NewLogger.func1(0xc0001163c0)
        /root/go/pkg/mod/github.com/baidubce/bce-sdk-go@v0.0.0-20180401121131-aa0c7bd66b01/util/log/logger.go:362 +0x145
created by github.com/baidubce/bce-sdk-go/util/log.NewLogger
        /root/go/pkg/mod/github.com/baidubce/bce-sdk-go@v0.0.0-20180401121131-aa0c7bd66b01/util/log/logger.go:359 +0xda

goroutine 21 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00012ca00)
        /root/go/pkg/mod/go.opencensus.io@v0.21.0/stats/view/worker.go:154 +0x105
created by go.opencensus.io/stats/view.init.0
        /root/go/pkg/mod/go.opencensus.io@v0.21.0/stats/view/worker.go:32 +0x57
```
**What you expected to happen**:
正常挂载
**How to reproduce it (as minimally and precisely as possible)**:
执行挂载命令
**Anything else we need to know?**:

**Environment**:
- JuiceFS version (use `./juicefs --version`):
- 0.9.3-22 (2021-01-25 8fcee47)
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g: `cat /etc/os-release`):
- NAME="CentOS Linux"
VERSION="8 (Core)"
- Kernel (e.g. `uname -a`):
- 4.18.0-167.el8.x86_64 #10 SMP Fri Oct 30 14:35:31 CST 2020 x86_64 x86_64 x86_64 GNU/Linux
- Object storage (cloud provider and region):
- Redis info (version, cloud provider managed or self maintained):
 Redis server v=5.0.3 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=28849dbea6f07cc8
- Network connectivity (JuiceFS to Redis, JuiceFS to object storage):
- Others:

**Comment by davies** [comment] 2021-01-26 06:48
@yunwoniu Can you reproduce it every time? How did you build it?

**Comment by davies** [comment] 2021-01-28 03:30
After discussed offline, this could be caused by customised runtime, we will try to build static-linked version, and try again.

**Comment by davies** [comment] 2021-02-22 04:09
We provide static-linked binary already, and can not reproduce this, close this for now.

**Closed by davies** 2021-02-22 04:09 UTC
Labels: kind/bug
