### ISSUE TITLE
Encounter `InvalidAccessKeyId` error when accessing S3 gateway deployed on Kubernetes

### ISSUE THREAD

**Issue by xiaogaozi** [juicedata/juicefs#1417] opened 2022-02-11 10:03 UTC
**What happened**:

When accessing S3 gateway deployed on Kubernetes through AWS CLI, it returns `InvalidAccessKeyId` error, e.g.:

```sh
$ kubectl get svc -n kube-system | grep juicefs
juicefs-s3-gateway        ClusterIP   1.2.3.4   <none>        9000/TCP,9567/TCP                 19m

$ aws --endpoint-url http://1.2.3.4:9000 s3 ls

An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The Access Key Id you provided does not exist in our records.
```

But if the S3 gateway is deployed outside of Kubernetes, AWS CLI could access it normally.

**What you expected to happen**:

AWS CLI should be able to access the S3 gateway normally.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy JuiceFS S3 gateway in Kubernetes (use this [YAML](https://github.com/juicedata/juicefs/blob/main/deploy/juicefs-s3-gateway.yaml))
2. Setup AWS CLI through `aws configure` command. The `Access Key ID` is equal to `MINIO_ROOT_USER` and `Secret Access Key` is equal to `MINIO_ROOT_PASSWORD`.
3. Access JuiceFS S3 gateway through AWS CLI, e.g. `aws s3 ls`.

**Anything else we need to know?**

N/A

**Environment**:

- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained): MinIO
- Metadata engine info (version, cloud provider managed or self maintained): MySQL
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zwwhdls** [comment] 2022-02-17 08:23
Can't reproduce. After inspection, it is caused by wrong secretKey in Secret. Closing.

**Closed by zwwhdls** 2022-02-17 08:23 UTC
