### ISSUE TITLE
Mounting a fs with postgres + search_path throws database is not formatted, please run `juicefs format` 

### ISSUE THREAD

**Issue by danielband** [juicedata/juicefs#2895] opened 2022-10-22 10:37 UTC
**What happened**:
Mounting an s3 compatibel fs with postgres + schema as meta storage  throws `database is not formatted`. Executing without setting search_path and thus using public works fine.

**What you expected to happen**:
The fs to be mounted error free

**How to reproduce it (as minimally and precisely as possible)**:
```
juicefs format--storage s3 --bucket https://sos-de-muc-1.exo.io/testjuice-pgsql   --access-key xxx  --secret-key xxx postgres://user:pass@dburl/db?search_path=schema pgjuice
Volume is formatted as {
  "Name": "pgjuice",
  "UUID": "33e5fe46-0fff-4a06-83c0-64251ef64df4",
  "Storage": "s3",
  "Bucket": "https://sos-de-muc-1.exo.io/testjuice-pgsql",
  "AccessKey": "vvvv",
  "SecretKey": "removed",
  "BlockSize": 4096,
  "Compression": "none",
  "KeyEncrypted": true,
  "TrashDays": 1,
  "MetaVersion": 1
} [format.go:472]
```

```
juicefs mount --background postgres://user:pass@dburl/db?search_path=schema /mnt/pgjuice
2022/10/22 10:07:12.533714 juicefs[32846] <INFO>: Meta address: postgres://xxxx?search_path=schema [interface.go:402]
2022/10/22 10:07:12.545518 juicefs[32846] <WARNING>: The latency to database is too high: 11.463676ms [sql.go:203]
2022/10/22 10:07:12.548892 juicefs[32846] <FATAL>: load setting: database is not formatted, please run `juicefs format ...` first [main.go:31]
```

**Anything else we need to know?**

**Environment**:
- juicefs version 1.0.2+2022-10-13.514ef03
- Debian 11
- Kernel (e.g. `uname -a`): 5.10.0-10-amd64 # 1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux
- Object storage (cloud provider and region, or self maintained): Managed Exoscale SOS Germany Munich 
- Metadata engine info (version, cloud provider managed or self maintained): Managed Postgres 14 on Exoscale

**Comment by zhijian-pro** [comment] 2022-10-24 02:37
I didn't reproduce this problem. 
Can you exec `show search_path` on postgres use user same as format?
`juicefs format--storage s3 --bucket https://sos-de-muc-1.exo.io/testjuice-pgsql   --access-key xxx  --secret-key xxx postgres://user:pass@dburl/db?search_path=schema pgjuice` can be exec success representative table has been established, so you can check which schema has jfs table(jfs_xxx).

**Comment by danielband** [comment] 2022-10-24 03:16
@zhijian-pro The schema is in the users search_path. As for the schema, all tables seems are present. Is there anything else I can check?

**Comment by zhijian-pro** [comment] 2022-10-24 07:03
I want to know the output of `show search_path`.   
In addition, I want to know which schema the table was established in when the format.

**Comment by danielband** [comment] 2022-10-24 09:14
> I want to know the output of `show search_path`. In addition, I want to know which schema the table was established in when the format.

search_path: juice, public, "$user"
Schema 'juice' contains all jfs_xxx tables.

**Comment by zhijian-pro** [comment] 2022-10-24 09:39
OK,if you want use the `juice` schema, you should exec `juicefs format--storage s3 --bucket https://sos-de-muc-1.exo.io/testjuice-pgsql   --access-key xxx  --secret-key xxx postgres://user:pass@dburl/db?search_path=juice pgjuice` and then `juicefs mount  postgres://user:pass@dburl/db?search_path=juice  /mountpoint`
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/31313340/197496948-69bc9b97-f96d-4a38-b20d-b4ba953413ab.png">
doc https://juicefs.com/docs/community/databases_for_metadata/#postgresql

**Comment by zhijian-pro** [comment] 2022-10-24 09:47
I found no problems in my test.
<img width="1686" alt="image" src="https://user-images.githubusercontent.com/31313340/197498629-cc170823-0c8c-456e-b76f-325cfe0d7a30.png">
<img width="2557" alt="image" src="https://user-images.githubusercontent.com/31313340/197498648-0fc8436b-230a-4d8d-897d-16b1ec0bf512.png">

**Comment by zhijian-pro** [comment] 2022-10-25 00:48
As far as I know, this should be a standard behavior. You can tell me your version or supplier.

**Comment by danielband** [comment] 2022-10-25 01:25
I am using v14.5 on [Exoscale/Aiven](https://community.exoscale.com/documentation/dbaas/managed-postgresql/). Anyway, thanks for your effort.

**Comment by davies** [comment] 2022-11-14 03:07
can't reproduce it, close it for now.

**Closed by davies** 2022-11-14 03:07 UTC
